### ISSUE TITLE
Dummy Variable Trap

### ISSUE THREAD

**Issue by salihgunduz** [jeslago/epftoolbox#11]
In the LEAR model, the day of the week variable is given as a 7 dummy.  Does this cause a "dummy variable trap" problem?

**Comment by jeslago** [comment]
Do you mean collinearity issues because the 7 variables are not linearly independent? My first intution would be to say that it might indeed be problematic. @gmarcjasz what do you think about it? Can we change the model to only have 6 dummies since the 7th day will be given by the other 6 variables being 0?

**Comment by salihgunduz** [comment]
Thanks. Yes, I meant multicollinearity. As you mentioned "Dropping One Out " is the ideal solution. But I have found that regularization terms prevent this problem. It is explained in this [book.](https://link.springer.com/chapter/10.1007/978-0-585-25657-3_37#:~:text=Multicollinearity%20is%20a%20problem%20because,coefficient%20will%20be%20statistically%20significant)  ()  I run a simple experiment with 6 and 7 dummies the results was closer.

**Comment by jeslago** [comment]
Actually makes sense that the regularization (L1) prevents this issue. I have checked online and I found this [resource](https://waterprogramming.wordpress.com/2017/02/22/dealing-with-multicollinearity-a-brief-overview-and-introduction-to-tolerant-methods/) explaining why with LASSO it is not a problem.

Can you share the results you have for 6 and 7 dummies?

**Comment by salihgunduz** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1313bc28-7fff-155d-74a8-5dc33c0b1912"><div dir="ltr" style="margin-left:0pt;" align="left">

LEAR | BE | FR | DE | NP
-- | -- | -- | -- | --
With 6 Dummies | 6.19117 | 4.57445 | 4.73951 | 1.97137
With 7 Dummies | 6.20885 | 4.58352 | 4.75500 | 1.96982

</div></b>
