### ISSUE TITLE
Database url doesn't exist

### ISSUE THREAD

**Issue by lebeand** [jeslago/epftoolbox#21]
The url https://sandbox.zenodo.org/record/632147 doesn't exist.

https://github.com/jeslago/epftoolbox/blob/d9cf47e2f892529ff06aa229409e80b929b6e6c9/docs/modules/data_extract.rst?plain=1#L6

**Comment by jeslago** [comment]
It has been fixed!

**Comment by ClaudiaShu** [comment]
Hi, the link leads to a "Page not found" error.
