### ISSUE TITLE
Calibration_window not used in recalibrate_and_forecast_next_day LEAR

### ISSUE THREAD

**Issue by robclaes** [jeslago/epftoolbox#30]
The `recalibrate_and_forecast_next_day` method of the LEAR model does not use its `calibration_window` argument but "incorrectly" uses `self.calibration_window`.
https://github.com/jeslago/epftoolbox/blob/3e0cd68e4c8d83e8574afd9fc4fc189d88e678b6/epftoolbox/models/_lear.py#L288C53-L288C71

**Comment by jeslago** [comment]
Thanks for noticing this. Can you create a pull request to fix it?
