### ISSUE TITLE
DNN models 'path_hyperparameters_folder'

### ISSUE THREAD

**Issue by salihgunduz** [jeslago/epftoolbox#4]
LEAR examples are working fine, but I got error when I run _"optimizing_hyperparameters_dnn.py"_ 

**TypeError: _hyperopt_objective() got an unexpected keyword argument 'path_hyperparameters_folder'. I use windows 10. Is anything wrong about paths?**

And _"recalibrating_dnn_simplified.py"_ gives this error:
**FileNotFoundError: [Errno 2] No such file or directory: '.\\experimental_files\\hyper_nl2_datPJM_YT2_SF_CW4_1'**

**Comment by salihgunduz** [comment]
It is solved by deleting "path_hyperparameters_folder=path_hyperparameters_folder," from fmin_objective function in _dnn_hyperopt.py.

**Comment by jeslago** [comment]
Dear Salih,

thanks for finding the bug. The library it is still on early stages of development so I guess it has some bugs left.

`path_hyperparameters_folder` was an old parameter that is no longer in use in that function. I have fixed the code to correct this.

Again, thanks a lot for finding the issue.

**Comment by salihgunduz** [comment]
> Dear Salih,
> 
> thanks for finding the bug. The library it is still on early stages of development so I guess it has some bugs left.
> 
> `path_hyperparameters_folder` was an old parameter that is no longer in use in that function. I have fixed the code to correct this.
> 
> Again, thanks a lot for finding the issue.

Indeed I am thankful for this great library. I hope I will contribute the library more.
