### ISSUE TITLE
Parameter names. 

### ISSUE THREAD

**Issue by salihgunduz** [jeslago/epftoolbox#5]
trials_file_name must start the same like _'DNN_hyperparameters_nl'_ in **_dnn_hyperopt.py** and **_dnn.py**.

'batch_normalization' key is not 'BN'
self.model = DNNModel(neurons=neurons, n_features=Xtrain.shape[-1], 
                              dropout=self.best_hyperparameters['dropout'], 
                              batch_normalization=self.best_hyperparameters['**BN**'], 
                              **batch_normalization=self.best_hyperparameters['batch_normalization'],** 
                              lr=self.best_hyperparameters['lr'], verbose=False,
                              optimizer='adam', activation=self.best_hyperparameters['activation'],
                              epochs_early_stopping=20, scaler=self.scaler, loss='mae',

**Comment by salihgunduz** [comment]
Dear Lago,
Nord Pool data has some errors at daylight change times because of the data format.  For example 45,77 was recorded like 45770.

**Comment by jeslago** [comment]
> trials_file_name must start the same like _'DNN_hyperparameters_nl'_ in **_dnn_hyperopt.py** and **_dnn.py**.
> 
> 'batch_normalization' key is not 'BN'
> self.model = DNNModel(neurons=neurons, n_features=Xtrain.shape[-1],
> dropout=self.best_hyperparameters['dropout

Thanks for this, I will fix it.

**Comment by jeslago** [comment]
> Dear Lago,
> Nord Pool data has some errors at daylight change times because of the data format. For example 45,77 was recorded like 45770.

Can you provide an example? Do you mean the data has an error in the [database](https://sandbox.zenodo.org/record/632147) or the error appears when reading the database with the epftoolbox library.

**Comment by salihgunduz** [comment]
Yes data has erros at dates:
31/03/2013 02:00
30/03/2014 02:00
29/03/2015 02:00
27/03/2016 02:00
26/03/2017 02:00
25/03/2018 02:00
If you check these dates you will realize the error.
For example, NordPool data at Date 27/03/2016 02:00  =  the value must be 15,07  but it is 15072(15 thousand). 
Thanks.

**Comment by salihgunduz** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/38071762/93257307-4fe08480-f7a5-11ea-8785-19cb8a955c6f.jpg)

**Comment by salihgunduz** [comment]
Sorry database look ok. I think it was about my conversion.
