### ISSUE TITLE
LEAR bug: exogeneous used at D-2, should be D-7

### ISSUE THREAD

**Issue by MichalJarema** [jeslago/epftoolbox#8]
In file _lear.py, line 240, function build_and_split_XY():

There is 
   for past_day in [1,2]:

Should be:
   for past_day in [1,7]:

**Comment by jeslago** [comment]
@gmarcjasz What do you think of this?

**Comment by gmarcjasz** [comment]
It should be [1, 7] as Michal suggests - I tested both versions and the difference (depending on the dataset) of MAE and RMSE metrics is between 0 and 1% - but in all cases the corrected version is not worse. The code will be updated to reflect that change.
